# Auto-generated from responses_api.py
# Model: InputImageContentParamAutoParam

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Literal, Optional

from pydantic import BaseModel, Field, constr


# Model dependencies
from .detail_enum import DetailEnum


class InputImageContentParamAutoParam(BaseModel):
    type: Literal["InputImageContentParamAutoParam"] = Field(
        ..., description="The type of the input item. Always `input_image`."
    )
    image_url: Optional[constr(max_length=20971520)] = None
    file_id: Optional[str] = None
    detail: Optional[DetailEnum] = None
