# Auto-generated from responses_api.py
# Model: InputItem

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import RootModel



# Model dependencies
from .easy_input_message import EasyInputMessage
from .item import Item
from .item_reference_param import ItemReferenceParam


class InputItem(RootModel[Union[EasyInputMessage, Item, ItemReferenceParam]]):
    pass
