# Auto-generated from responses_api.py
# Model: InputTextContentParam

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Literal

from pydantic import BaseModel, Field, constr


class InputTextContentParam(BaseModel):
    type: Literal["InputTextContentParam"] = Field(
        ..., description="The type of the input item. Always `input_text`."
    )
    text: constr(max_length=10485760) = Field(
        ..., description="The text input to the model."
    )
