# Auto-generated from responses_api.py
# Model: OutputContent

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Union

from pydantic import RootModel



# Model dependencies
from .output_text_content import OutputTextContent
from .reasoning_text_content import ReasoningTextContent
from .refusal_content import RefusalContent


class OutputContent(RootModel[Union[OutputTextContent, RefusalContent, ReasoningTextContent]]):
    pass
